/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BridgetRouteImport } from './routes/bridget'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LeadRouteImport } from './routes/lead'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicareBasicsRouteImport } from './routes/medicare-basics'
import { Route as NeedsAnalysisRouteImport } from './routes/needs-analysis'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgetRoute = BridgetRouteImport.update({
  id: '/bridget',
  path: '/bridget',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadRoute = LeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicareBasicsRoute = MedicareBasicsRouteImport.update({
  id: '/medicare-basics',
  path: '/medicare-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsAnalysisRoute = NeedsAnalysisRouteImport.update({
  id: '/needs-analysis',
  path: '/needs-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridget': typeof BridgetRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/lead': typeof LeadRoute
  '/login': typeof LoginRoute
  '/medicare-basics': typeof MedicareBasicsRoute
  '/needs-analysis': typeof NeedsAnalysisRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/screener': typeof ScreenerRoute
  '/team': typeof TeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridget': typeof BridgetRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/lead': typeof LeadRoute
  '/login': typeof LoginRoute
  '/medicare-basics': typeof MedicareBasicsRoute
  '/needs-analysis': typeof NeedsAnalysisRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/screener': typeof ScreenerRoute
  '/team': typeof TeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridget': typeof BridgetRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/lead': typeof LeadRoute
  '/login': typeof LoginRoute
  '/medicare-basics': typeof MedicareBasicsRoute
  '/needs-analysis': typeof NeedsAnalysisRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/screener': typeof ScreenerRoute
  '/team': typeof TeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridget'
    | '/compare'
    | '/contact'
    | '/lead'
    | '/login'
    | '/medicare-basics'
    | '/needs-analysis'
    | '/portal'
    | '/privacy'
    | '/screener'
    | '/team'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridget'
    | '/compare'
    | '/contact'
    | '/lead'
    | '/login'
    | '/medicare-basics'
    | '/needs-analysis'
    | '/portal'
    | '/privacy'
    | '/screener'
    | '/team'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bridget'
    | '/compare'
    | '/contact'
    | '/lead'
    | '/login'
    | '/medicare-basics'
    | '/needs-analysis'
    | '/portal'
    | '/privacy'
    | '/screener'
    | '/team'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgetRoute: typeof BridgetRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  LeadRoute: typeof LeadRoute
  LoginRoute: typeof LoginRoute
  MedicareBasicsRoute: typeof MedicareBasicsRoute
  NeedsAnalysisRoute: typeof NeedsAnalysisRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ScreenerRoute: typeof ScreenerRoute
  TeamRoute: typeof TeamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridget': {
      id: '/bridget'
      path: '/bridget'
      fullPath: '/bridget'
      preLoaderRoute: typeof BridgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead': {
      id: '/lead'
      path: '/lead'
      fullPath: '/lead'
      preLoaderRoute: typeof LeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicare-basics': {
      id: '/medicare-basics'
      path: '/medicare-basics'
      fullPath: '/medicare-basics'
      preLoaderRoute: typeof MedicareBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-analysis': {
      id: '/needs-analysis'
      path: '/needs-analysis'
      fullPath: '/needs-analysis'
      preLoaderRoute: typeof NeedsAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgetRoute: BridgetRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  LeadRoute: LeadRoute,
  LoginRoute: LoginRoute,
  MedicareBasicsRoute: MedicareBasicsRoute,
  NeedsAnalysisRoute: NeedsAnalysisRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ScreenerRoute: ScreenerRoute,
  TeamRoute: TeamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
